### ISSUE TITLE
How to create a repository test?

### ISSUE THREAD

**Issue by LiveNathan** [xdev-software/spring-data-eclipse-store#141]
https://github.com/xdev-software/spring-data-eclipse-store/blob/991d3755a59ce66eff82071fbcf602cbd3ccf3df/spring-data-eclipse-store-demo/src/test/java/software/xdev/spring/data/eclipse/store/demo/simple/SimpleDemoApplicationTest.java#L16

Sorry to make this an issue. I don't see a Discussions section. 

I'd REALLY love to see an example of a repository test similar to the kind of JDBC tests I'm familiar with like [this one](https://github.com/soulpatch/song-themes/blob/main/src/test/java/com/songthematic/songthemes/adapter/out/jdbc/JdbcSongRepositoryTest.java)

I got started, but I'm not sure where to go from here:

```java
@Tag("database")
@Disabled("until I figure it out")
class ClockEclipseRepositoryTest {
    @Autowired
    EclipseClockRepository eclipseClockRepository;

    @Test
    void canReadAndWriteClockEvents() throws Exception {
        ClockEvent clockInEvent = new ClockEvent(ClockService.fixed(), ClockEventType.IN);
        eclipseClockRepository.save(clockInEvent);
        List<ClockEvent> actualEvents = eclipseClockRepository.findAll();

        assertThat(actualEvents).hasSize(1);
    }

}
```

**Comment by JohannesRabauer** [comment]
We have multiple kind of tests. The one you've linked is a basic test for booting the demo. 
But we many unit tests just like the one you described in your example: https://github.com/xdev-software/spring-data-eclipse-store/blob/991d3755a59ce66eff82071fbcf602cbd3ccf3df/spring-data-eclipse-store/src/test/java/software/xdev/spring/data/eclipse/store/integration/shared/tests/SimpleSingleTest.java#L61
or
https://github.com/xdev-software/spring-data-eclipse-store/blob/991d3755a59ce66eff82071fbcf602cbd3ccf3df/spring-data-eclipse-store/src/test/java/software/xdev/spring/data/eclipse/store/integration/isolated/tests/lazy/LazyTest.java#L70

So you should be easily be able to build this kind of test yourself.
Just pay close attention to the configuration and you should be fine. Also, please note that we are not using Testcontainers like in your linked JdbcSongRepositoryTest.

**Comment by LiveNathan** [comment]
Thank you so much! Can't wait to try it out.
